export default {
  FETCH_REDDIT_DETAIL_REQUEST: 'FETCH_REDDIT_DETAIL_REQUEST',
  FETCH_REDDIT_DETAIL_SUCCESS: 'FETCH_REDDIT_DETAIL_SUCCESS',
  FETCH_REDDIT_DETAIL_FAILURE: 'FETCH_REDDIT_DETAIL_FAILURE',
}
